### PR TITLE
A little PR that adds MP3 downloads instead of M4A.

### PR DESCRIPTION
**Pull request by alexmercerind**
This PR from branch **vnext** has:

- /trackdownload now gives MP3 downloads, which results in following changes and benefits:
  - Fixes the container, now tracks have proper bitrate mentioned
  - Some downloaded files could not be seeked sometimes, sending files in MP3 fixes occasionally Dash-M4A responses (instead of AAC)
- Another little change is that /trackdownload now no longer makes /trackinfo request, if file was already downloaded.
- I modified requirements.txt to use ytmusicapi from master on GitHub instead of PyPI (we want those new fixes).

After above changes, you need to have FFmpeg in your Heroku app. There is a build-pack available for that (see README). You need to add that & also the python one.

AT THE MOMENT HOWEVER, Harmonoid isn't ready to deal with MP3s. (Just need to change file handling, audio library will take care of rest itself).

### CODE REVIEW

**Comment by raitonoberu** [comment]
Hi, @alexmercerind!
Sorry, I didn't check GH for a few days.
Good job. This should work fine, but Mutagen is not asynchronous. I will rewrite the file as soon as I get home (you can also rewrite it yourself).

Thanks!

**Comment by alexmercerind** [comment]
👋 @raitonoberu!
Okay, I will do it.

**Comment by alexmercerind** [comment]
I packed all the mutagen actions under same async function (```init()```). Looks more readable.

**Comment by alexmercerind** [comment]
[vnext](https://github.com/raitonoberu/harmonoid-service/tree/vnext) 🔖

**Review by raitonoberu — APPROVED** [review]
Well done. I think it's too early to merge branches, because (as you said) the frontend isn't ready yet.

**Comment by alexmercerind** [comment]
Yeah indeed, it is early. I think we should close this for the time being. 
We'll reopen when I update the stuff & resolve the clash between Android & Windows.
Still I'll try to find a way to decode MPEG AAC & DASH streams somehow.

**Pull request closed without merging**
